[theme]
primaryColor="#005032"
backgroundColor="#F3950E"
secondaryBackgroundColor="#FAEAC4"
textColor="#000000"
font="sans serif"

[server]
folderWatchBlacklist = ['/data/', '/ml/', '/utils/', '/temp/', ]
